Add readthedocs image
stefanDeveloper/heiDGAF pull request #27
Opened 2024-09-25 09:59 UTC by stefanDeveloper

2024-09-25 10:00 UTC, stefanDeveloper commented
Related to #27, however I had a problem updating the PR in time before it got merged :D

2024-09-25 10:09 UTC, lamr02n requested changes
See comment on the readthedocs logo.

2024-09-25 10:09 UTC, lamr02n commented on assets/heidgaf_logo_readthedocs.png
The logo seems too big in relation to the name. I think we should make it smaller.

That's how it looks on readthedocs:
![image](https://github.com/user-attachments/assets/f642438d-8a82-42bc-a560-96f112db2b72)

2024-09-25 11:16 UTC, stefanDeveloper commented on assets/heidgaf_logo_readthedocs.png
Yes, I quickly adapted it without checking. Another thing is the view with dark mode.

2024-09-27 07:01 UTC, stefanDeveloper commented on assets/heidgaf_logo_readthedocs.png
![Screenshot 2024-09-27 at 09 00 36](https://github.com/user-attachments/assets/0a49c86e-f900-42c6-89c2-44fe6040df60)
![Screenshot 2024-09-27 at 09 00 42](https://github.com/user-attachments/assets/4717aa13-cde7-4e8c-ba75-724e324b2c05)

I adapted the size.

2024-09-28 14:04 UTC, lamr02n commented on assets/heidgaf_logo_readthedocs.png
I like it!

2024-09-28 14:14 UTC, lamr02n approved these changes
Awesome, looks good!

2024-09-28 14:15 UTC, merged